# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1035, 473)
        Form.setStyleSheet("font-family:微軟正黑體;\n"
"font-weight: bold;")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 30)
        self.verticalLayout_4.setSpacing(30)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;\n"
"padding: 5px;\n"
"border-bottom: 10px solid black;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(30, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.load_config_btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_config_btn.sizePolicy().hasHeightForWidth())
        self.load_config_btn.setSizePolicy(sizePolicy)
        self.load_config_btn.setObjectName("load_config_btn")
        self.horizontalLayout_4.addWidget(self.load_config_btn)
        self.config_path = QtWidgets.QLabel(Form)
        self.config_path.setText("")
        self.config_path.setObjectName("config_path")
        self.horizontalLayout_4.addWidget(self.config_path)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;\n"
"padding: 5px;\n"
"border-bottom: 10px solid black;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(30, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.platform = QtWidgets.QLabel(Form)
        self.platform.setObjectName("platform")
        self.gridLayout.addWidget(self.platform, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.trigger_idx = QtWidgets.QLabel(Form)
        self.trigger_idx.setObjectName("trigger_idx")
        self.gridLayout.addWidget(self.trigger_idx, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.project_path = QtWidgets.QLabel(Form)
        self.project_path.setObjectName("project_path")
        self.gridLayout.addWidget(self.project_path, 1, 1, 1, 1)
        self.gen_num = QtWidgets.QLabel(Form)
        self.gen_num.setObjectName("gen_num")
        self.gridLayout.addWidget(self.gen_num, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.step = QtWidgets.QLabel(Form)
        self.step.setObjectName("step")
        self.gridLayout.addWidget(self.step, 4, 1, 1, 1)
        self.param_name = QtWidgets.QLabel(Form)
        self.param_name.setObjectName("param_name")
        self.gridLayout.addWidget(self.param_name, 5, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_8)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Load Config"))
        self.load_config_btn.setToolTip(_translate("Form", "Config會指定要調\n"
"哪一個平台(c6 or c7)\n"
"哪一包project\n"
"哪一個region\n"
"哪些參數\n"
"參數範圍的設定與精度\n"
"要隨機生成多少組參數等等"))
        self.load_config_btn.setText(_translate("Form", "Load Config"))
        self.label_7.setText(_translate("Form", "Config Info"))
        self.platform.setText(_translate("Form", "#"))
        self.label.setText(_translate("Form", "platform"))
        self.trigger_idx.setText(_translate("Form", "#"))
        self.label_3.setText(_translate("Form", "trigger_idx(region)"))
        self.label_2.setText(_translate("Form", "project路徑"))
        self.project_path.setText(_translate("Form", "#"))
        self.gen_num.setText(_translate("Form", "#"))
        self.label_6.setText(_translate("Form", "每個參數的精度(四捨五入到第幾位)"))
        self.label_5.setText(_translate("Form", "要隨機產生幾組參數"))
        self.label_8.setText(_translate("Form", "要調的參數"))
        self.step.setText(_translate("Form", "#"))
        self.param_name.setText(_translate("Form", "#"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
