# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(832, 469)
        Form.setStyleSheet("font-family:微軟正黑體;\n"
"font-weight: bold;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 818, 455))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.setting_layout = QtWidgets.QVBoxLayout()
        self.setting_layout.setObjectName("setting_layout")
        self.project_layout = QtWidgets.QGridLayout()
        self.project_layout.setObjectName("project_layout")
        self.load_img_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_img_btn.sizePolicy().hasHeightForWidth())
        self.load_img_btn.setSizePolicy(sizePolicy)
        self.load_img_btn.setObjectName("load_img_btn")
        self.project_layout.addWidget(self.load_img_btn, 0, 0, 1, 1)
        self.img_path = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img_path.setObjectName("img_path")
        self.project_layout.addWidget(self.img_path, 0, 1, 1, 1)
        self.project_layout.setColumnStretch(0, 2)
        self.project_layout.setColumnStretch(1, 5)
        self.setting_layout.addLayout(self.project_layout)
        self.verticalLayout.addLayout(self.setting_layout)
        self.select_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.select_btn.setObjectName("select_btn")
        self.verticalLayout.addWidget(self.select_btn)
        self.ROI_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_label.sizePolicy().hasHeightForWidth())
        self.ROI_label.setSizePolicy(sizePolicy)
        self.ROI_label.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.ROI_label.setMouseTracking(True)
        self.ROI_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ROI_label.setWordWrap(True)
        self.ROI_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.ROI_label.setObjectName("ROI_label")
        self.verticalLayout.addWidget(self.ROI_label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.load_img_btn.setText(_translate("Form", "Load img"))
        self.img_path.setText(_translate("Form", "#"))
        self.select_btn.setText(_translate("Form", "select"))
        self.ROI_label.setText(_translate("Form", "ROI:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
