# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QSize



class LogicHandler:
   def __init__(self, ui_form):
       self.ui_form = ui_form
       self.connections = []


       # Connect signals to slots
       self.connect_signals()


   def connect_signals(self):
       self.ui_form.lineEdit_LV1_2.textChanged.connect(
           lambda text: self.update_LV_line_edit(text, self.ui_form.lineEdit_LV2))
       self.ui_form.lineEdit_LV2_2.textChanged.connect(
           lambda text: self.update_LV_line_edit(text, self.ui_form.lineEdit_LV3))
       self.ui_form.lineEdit_LV3_2.textChanged.connect(
           lambda text: self.update_LV_line_edit(text, self.ui_form.lineEdit_LV4))
       self.ui_form.lineEdit_LV4_2.textChanged.connect(
           lambda text: self.update_LV_line_edit(text, self.ui_form.lineEdit_LV5))
       self.ui_form.lineEdit_LV5_2.textChanged.connect(
           lambda text: self.update_LV_line_edit(text, self.ui_form.lineEdit_LV6))
       self.ui_form.lineEdit_LV6_2.textChanged.connect(
           lambda text: self.update_LV_line_edit(text, self.ui_form.lineEdit_LV7))
       self.ui_form.lineEdit_LV7_2.textChanged.connect(
           lambda text: self.update_LV_line_edit(text, self.ui_form.lineEdit_LV8))
       self.ui_form.lineEdit_LV8_2.textChanged.connect(
           lambda text: self.update_LV_line_edit(text, self.ui_form.lineEdit_LV9))
       self.ui_form.lineEdit_LV9_2.textChanged.connect(
           lambda text: self.update_LV_line_edit(text, self.ui_form.lineEdit_LV10))


       self.ui_form.lineEdit_DR1_2.textChanged.connect(
           lambda text: self.update_DR_line_edit(text, self.ui_form.lineEdit_DR2))
       self.ui_form.lineEdit_DR2_2.textChanged.connect(
           lambda text: self.update_DR_line_edit(text, self.ui_form.lineEdit_DR3))
       self.ui_form.lineEdit_DR3_2.textChanged.connect(
           lambda text: self.update_DR_line_edit(text, self.ui_form.lineEdit_DR4))
       self.ui_form.lineEdit_DR4_2.textChanged.connect(
           lambda text: self.update_DR_line_edit(text, self.ui_form.lineEdit_DR5))
       self.ui_form.lineEdit_DR5_2.textChanged.connect(
           lambda text: self.update_DR_line_edit(text, self.ui_form.lineEdit_DR6))
       self.ui_form.lineEdit_DR6_2.textChanged.connect(
           lambda text: self.update_DR_line_edit(text, self.ui_form.lineEdit_DR7))
       self.ui_form.lineEdit_DR7_2.textChanged.connect(
           lambda text: self.update_DR_line_edit(text, self.ui_form.lineEdit_DR8))
       self.ui_form.lineEdit_DR8_2.textChanged.connect(
           lambda text: self.update_DR_line_edit(text, self.ui_form.lineEdit_DR9))
       self.ui_form.lineEdit_DR9_2.textChanged.connect(
           lambda text: self.update_DR_line_edit(text, self.ui_form.lineEdit_DR10))


   def update_LV_line_edit(self, text, target_lineedit):
       target_lineedit.setText(text)
       if text == '180':
           target_lineedit.setText('')


   def update_DR_line_edit(self, text, target_lineedit):
       target_lineedit.setText(text)
       if text == '1000':
           target_lineedit.setText('')



class Ui_Form(object): 
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(620, 760)
        
        ##########0219
        # For scrollArea
        self.showLayout = QtWidgets.QHBoxLayout(Form)
        self.showLayout.setObjectName("showLayout")
        self.scrollArea_all = QtWidgets.QScrollArea(Form)
        self.scrollArea_all.setWidgetResizable(True)
        self.scrollArea_all.setObjectName("scrollArea_all")
        self.scrollAreaWidgetContents_all = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents_all.setGeometry(QtCore.QRect(0, 0, 500, 900))###
        # self.scrollAreaWidgetContents_all.setGeometry(QtCore.QRect(0, 0, 610, 750))###
        self.scrollAreaWidgetContents_all.setGeometry(QtCore.QRect(0, 0, 610, 500))
        self.scrollAreaWidgetContents_all.setObjectName("scrollAreaWidgetContents_all")
        self.allLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_all)
        self.allLayout.setObjectName("allLayout")
        #################

        self.widget_mid = QtWidgets.QWidget()
        # self.widget_mid.setGeometry(QtCore.QRect(20, 190, 531, 382))
        self.widget_mid.setObjectName("widget_mid")
        self.widget_mid.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_mid)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_LR_max = QtWidgets.QLabel(self.widget_mid)
        self.label_LR_max.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_LR_max.setObjectName("label_LR_max")
        self.gridLayout_3.addWidget(self.label_LR_max, 3, 0, 1, 1)
        self.label_RS_description = QtWidgets.QLabel(self.widget_mid)
        self.label_RS_description.setObjectName("label_RS_description")
        self.gridLayout_3.addWidget(self.label_RS_description, 1, 0, 1, 3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_DR10_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR10_2.setObjectName("lineEdit_DR10_2")
        self.gridLayout.addWidget(self.lineEdit_DR10_2, 9, 3, 1, 1)
        self.lineEdit_DR6_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR6_2.setObjectName("lineEdit_DR6_2")
        self.gridLayout.addWidget(self.lineEdit_DR6_2, 5, 3, 1, 1)
        self.lineEdit_DR7_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR7_2.setObjectName("lineEdit_DR7_2")
        self.gridLayout.addWidget(self.lineEdit_DR7_2, 6, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget_mid)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 6, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget_mid)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 9, 2, 1, 1)
        self.lineEdit_DR9_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR9_2.setObjectName("lineEdit_DR9_2")
        self.gridLayout.addWidget(self.lineEdit_DR9_2, 8, 3, 1, 1)
        self.lineEdit_DR6 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR6.setReadOnly(True)
        self.lineEdit_DR6.setObjectName("lineEdit_DR6")
        self.gridLayout.addWidget(self.lineEdit_DR6, 5, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_mid)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 3, 2, 1, 1)
        self.lineEdit_DR9 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR9.setReadOnly(True)
        self.lineEdit_DR9.setObjectName("lineEdit_DR9")
        self.gridLayout.addWidget(self.lineEdit_DR9, 8, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget_mid)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 2, 1, 1)
        self.lineEdit_DR7 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR7.setReadOnly(True)
        self.lineEdit_DR7.setObjectName("lineEdit_DR7")
        self.gridLayout.addWidget(self.lineEdit_DR7, 6, 1, 1, 1)
        self.lineEdit_DR8 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR8.setReadOnly(True)
        self.lineEdit_DR8.setObjectName("lineEdit_DR8")
        self.gridLayout.addWidget(self.lineEdit_DR8, 7, 1, 1, 1)
        self.label_DR8 = QtWidgets.QLabel(self.widget_mid)
        self.label_DR8.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_DR8.setObjectName("label_DR8")
        self.gridLayout.addWidget(self.label_DR8, 7, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget_mid)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 8, 2, 1, 1)
        self.label_DR10 = QtWidgets.QLabel(self.widget_mid)
        self.label_DR10.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_DR10.setObjectName("label_DR10")
        self.gridLayout.addWidget(self.label_DR10, 9, 0, 1, 1)
        self.label_DR2 = QtWidgets.QLabel(self.widget_mid)
        self.label_DR2.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_DR2.setObjectName("label_DR2")
        self.gridLayout.addWidget(self.label_DR2, 1, 0, 1, 1)
        self.label_DR7 = QtWidgets.QLabel(self.widget_mid)
        self.label_DR7.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_DR7.setObjectName("label_DR7")
        self.gridLayout.addWidget(self.label_DR7, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget_mid)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 7, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_mid)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 2, 1, 1)
        self.lineEdit_DR10 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR10.setReadOnly(True)
        self.lineEdit_DR10.setObjectName("lineEdit_DR10")
        self.gridLayout.addWidget(self.lineEdit_DR10, 9, 1, 1, 1)
        self.label_DR9 = QtWidgets.QLabel(self.widget_mid)
        self.label_DR9.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_DR9.setObjectName("label_DR9")
        self.gridLayout.addWidget(self.label_DR9, 8, 0, 1, 1)
        self.lineEdit_DR8_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR8_2.setObjectName("lineEdit_DR8_2")
        self.gridLayout.addWidget(self.lineEdit_DR8_2, 7, 3, 1, 1)
        self.lineEdit_DR5_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR5_2.setObjectName("lineEdit_DR5_2")
        self.gridLayout.addWidget(self.lineEdit_DR5_2, 4, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_mid)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 2, 1, 1)
        self.lineEdit_DR2_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR2_2.setObjectName("lineEdit_DR2_2")
        self.gridLayout.addWidget(self.lineEdit_DR2_2, 1, 3, 1, 1)
        self.label_DR4 = QtWidgets.QLabel(self.widget_mid)
        self.label_DR4.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_DR4.setObjectName("label_DR4")
        self.gridLayout.addWidget(self.label_DR4, 3, 0, 1, 1)
        self.lineEdit_DR1_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR1_2.setObjectName("lineEdit_DR1_2")
        self.gridLayout.addWidget(self.lineEdit_DR1_2, 0, 3, 1, 1)
        self.lineEdit_DR3 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR3.setReadOnly(True)
        self.lineEdit_DR3.setObjectName("lineEdit_DR3")
        self.gridLayout.addWidget(self.lineEdit_DR3, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_mid)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 2, 1, 1)
        self.lineEdit_DR3_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR3_2.setObjectName("lineEdit_DR3_2")
        self.gridLayout.addWidget(self.lineEdit_DR3_2, 2, 3, 1, 1)
        self.label_DR1 = QtWidgets.QLabel(self.widget_mid)
        self.label_DR1.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_DR1.setObjectName("label_DR1")
        self.gridLayout.addWidget(self.label_DR1, 0, 0, 1, 1)
        self.label_DR3 = QtWidgets.QLabel(self.widget_mid)
        self.label_DR3.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_DR3.setObjectName("label_DR3")
        self.gridLayout.addWidget(self.label_DR3, 2, 0, 1, 1)
        self.lineEdit_DR5 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR5.setReadOnly(True)
        self.lineEdit_DR5.setObjectName("lineEdit_DR5")
        self.gridLayout.addWidget(self.lineEdit_DR5, 4, 1, 1, 1)
        self.lineEdit_DR4_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR4_2.setObjectName("lineEdit_DR4_2")
        self.gridLayout.addWidget(self.lineEdit_DR4_2, 3, 3, 1, 1)
        self.lineEdit_DR1 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR1.setReadOnly(True)
        self.lineEdit_DR1.setObjectName("lineEdit_DR1")
        self.gridLayout.addWidget(self.lineEdit_DR1, 0, 1, 1, 1)
        self.lineEdit_DR4 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR4.setReadOnly(True)
        self.lineEdit_DR4.setObjectName("lineEdit_DR4")
        self.gridLayout.addWidget(self.lineEdit_DR4, 3, 1, 1, 1)
        self.lineEdit_DR2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_DR2.setReadOnly(True)
        self.lineEdit_DR2.setObjectName("lineEdit_DR2")
        self.gridLayout.addWidget(self.lineEdit_DR2, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_mid)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_DR5 = QtWidgets.QLabel(self.widget_mid)
        self.label_DR5.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_DR5.setObjectName("label_DR5")
        self.gridLayout.addWidget(self.label_DR5, 4, 0, 1, 1)
        self.label_DR6 = QtWidgets.QLabel(self.widget_mid)
        self.label_DR6.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_DR6.setObjectName("label_DR6")
        self.gridLayout.addWidget(self.label_DR6, 5, 0, 1, 1)
        self.label_DR_max = QtWidgets.QLabel(self.widget_mid)
        self.label_DR_max.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_DR_max.setObjectName("label_DR_max")
        self.gridLayout.addWidget(self.label_DR_max, 10, 0, 1, 4)
        self.gridLayout_3.addLayout(self.gridLayout, 2, 1, 2, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_LV1 = QtWidgets.QLabel(self.widget_mid)
        self.label_LV1.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_LV1.setObjectName("label_LV1")
        self.gridLayout_4.addWidget(self.label_LV1, 0, 0, 1, 1)
        self.lineEdit_LV1 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV1.setReadOnly(True)
        self.lineEdit_LV1.setObjectName("lineEdit_LV1")
        self.gridLayout_4.addWidget(self.lineEdit_LV1, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_mid)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 2, 1, 1)
        self.lineEdit_LV1_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV1_2.setObjectName("lineEdit_LV1_2")
        self.gridLayout_4.addWidget(self.lineEdit_LV1_2, 0, 3, 1, 1)
        self.label_LV2 = QtWidgets.QLabel(self.widget_mid)
        self.label_LV2.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_LV2.setObjectName("label_LV2")
        self.gridLayout_4.addWidget(self.label_LV2, 1, 0, 1, 1)
        self.lineEdit_LV2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV2.setReadOnly(True)
        self.lineEdit_LV2.setObjectName("lineEdit_LV2")
        self.gridLayout_4.addWidget(self.lineEdit_LV2, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_mid)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 2, 1, 1)
        self.lineEdit_LV2_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV2_2.setObjectName("lineEdit_LV2_2")
        self.gridLayout_4.addWidget(self.lineEdit_LV2_2, 1, 3, 1, 1)
        self.label_LV3 = QtWidgets.QLabel(self.widget_mid)
        self.label_LV3.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_LV3.setObjectName("label_LV3")
        self.gridLayout_4.addWidget(self.label_LV3, 2, 0, 1, 1)
        self.lineEdit_LV3 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV3.setReadOnly(True)
        self.lineEdit_LV3.setObjectName("lineEdit_LV3")
        self.gridLayout_4.addWidget(self.lineEdit_LV3, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_mid)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 2, 1, 1)
        self.lineEdit_LV3_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV3_2.setObjectName("lineEdit_LV3_2")
        self.gridLayout_4.addWidget(self.lineEdit_LV3_2, 2, 3, 1, 1)
        self.label_LV4 = QtWidgets.QLabel(self.widget_mid)
        self.label_LV4.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_LV4.setObjectName("label_LV4")
        self.gridLayout_4.addWidget(self.label_LV4, 3, 0, 1, 1)
        self.lineEdit_LV4 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV4.setReadOnly(True)
        self.lineEdit_LV4.setObjectName("lineEdit_LV4")
        self.gridLayout_4.addWidget(self.lineEdit_LV4, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_mid)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 2, 1, 1)
        self.lineEdit_LV4_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV4_2.setObjectName("lineEdit_LV4_2")
        self.gridLayout_4.addWidget(self.lineEdit_LV4_2, 3, 3, 1, 1)
        self.label_LV5 = QtWidgets.QLabel(self.widget_mid)
        self.label_LV5.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_LV5.setObjectName("label_LV5")
        self.gridLayout_4.addWidget(self.label_LV5, 4, 0, 1, 1)
        self.lineEdit_LV5 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV5.setReadOnly(True)
        self.lineEdit_LV5.setObjectName("lineEdit_LV5")
        self.gridLayout_4.addWidget(self.lineEdit_LV5, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_mid)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 4, 2, 1, 1)
        self.lineEdit_LV5_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV5_2.setObjectName("lineEdit_LV5_2")
        self.gridLayout_4.addWidget(self.lineEdit_LV5_2, 4, 3, 1, 1)
        self.label_LV6 = QtWidgets.QLabel(self.widget_mid)
        self.label_LV6.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_LV6.setObjectName("label_LV6")
        self.gridLayout_4.addWidget(self.label_LV6, 5, 0, 1, 1)
        self.lineEdit_LV6 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV6.setReadOnly(True)
        self.lineEdit_LV6.setObjectName("lineEdit_LV6")
        self.gridLayout_4.addWidget(self.lineEdit_LV6, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_mid)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 5, 2, 1, 1)
        self.lineEdit_LV6_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV6_2.setObjectName("lineEdit_LV6_2")
        self.gridLayout_4.addWidget(self.lineEdit_LV6_2, 5, 3, 1, 1)
        self.label_LV7 = QtWidgets.QLabel(self.widget_mid)
        self.label_LV7.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_LV7.setObjectName("label_LV7")
        self.gridLayout_4.addWidget(self.label_LV7, 6, 0, 1, 1)
        self.lineEdit_LV7 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV7.setReadOnly(True)
        self.lineEdit_LV7.setObjectName("lineEdit_LV7")
        self.gridLayout_4.addWidget(self.lineEdit_LV7, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_mid)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 6, 2, 1, 1)
        self.lineEdit_LV7_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV7_2.setObjectName("lineEdit_LV7_2")
        self.gridLayout_4.addWidget(self.lineEdit_LV7_2, 6, 3, 1, 1)
        self.label_LV8 = QtWidgets.QLabel(self.widget_mid)
        self.label_LV8.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_LV8.setObjectName("label_LV8")
        self.gridLayout_4.addWidget(self.label_LV8, 7, 0, 1, 1)
        self.lineEdit_LV8 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV8.setReadOnly(True)
        self.lineEdit_LV8.setObjectName("lineEdit_LV8")
        self.gridLayout_4.addWidget(self.lineEdit_LV8, 7, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_mid)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 7, 2, 1, 1)
        self.lineEdit_LV8_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV8_2.setObjectName("lineEdit_LV8_2")
        self.gridLayout_4.addWidget(self.lineEdit_LV8_2, 7, 3, 1, 1)
        self.label_LV9 = QtWidgets.QLabel(self.widget_mid)
        self.label_LV9.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_LV9.setObjectName("label_LV9")
        self.gridLayout_4.addWidget(self.label_LV9, 8, 0, 1, 1)
        self.lineEdit_LV9 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV9.setReadOnly(True)
        self.lineEdit_LV9.setObjectName("lineEdit_LV9")
        self.gridLayout_4.addWidget(self.lineEdit_LV9, 8, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_mid)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 8, 2, 1, 1)
        self.lineEdit_LV9_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV9_2.setObjectName("lineEdit_LV9_2")
        self.gridLayout_4.addWidget(self.lineEdit_LV9_2, 8, 3, 1, 1)
        self.label_LV10 = QtWidgets.QLabel(self.widget_mid)
        self.label_LV10.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_LV10.setObjectName("label_LV10")
        self.gridLayout_4.addWidget(self.label_LV10, 9, 0, 1, 1)
        self.lineEdit_LV10 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV10.setReadOnly(True)
        self.lineEdit_LV10.setObjectName("lineEdit_LV10")
        self.gridLayout_4.addWidget(self.lineEdit_LV10, 9, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_mid)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 9, 2, 1, 1)
        self.lineEdit_LV10_2 = QtWidgets.QLineEdit(self.widget_mid)
        self.lineEdit_LV10_2.setObjectName("lineEdit_LV10_2")
        self.gridLayout_4.addWidget(self.lineEdit_LV10_2, 9, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_Reset = QtWidgets.QPushButton(self.widget_mid)
        self.btn_Reset.setObjectName("btn_Reset")
        self.gridLayout_2.addWidget(self.btn_Reset, 1, 0, 1, 1)
        self.btn_OpenFolder = QtWidgets.QPushButton(self.widget_mid)
        self.btn_OpenFolder.setObjectName("btn_OpenFolder")
        self.gridLayout_2.addWidget(self.btn_OpenFolder, 3, 0, 1, 1)
        self.btn_Category = QtWidgets.QPushButton(self.widget_mid)
        self.btn_Category.setObjectName("btn_Category")
        self.gridLayout_2.addWidget(self.btn_Category, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 2, 1, 1)
        self.label_RangeSettings = QtWidgets.QLabel(self.widget_mid)
        self.label_RangeSettings.setObjectName("label_RangeSettings")
        self.gridLayout_3.addWidget(self.label_RangeSettings, 0, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 3, 2, 1, 1)



        self.widget_top = QtWidgets.QWidget()
        # self.widget_top.setGeometry(QtCore.QRect(20, 10, 450, 171))
        self.widget_top.setObjectName("widget_top")
        self.widget_top.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
         
        
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_top)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_DataFolder = QtWidgets.QLabel(self.widget_top)
        self.label_DataFolder.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_DataFolder.setObjectName("label_DataFolder")
        self.gridLayout_6.addWidget(self.label_DataFolder, 1, 0, 1, 1)
        self.lineEdit_DataFolder = QtWidgets.QLineEdit(self.widget_top)
        # self.lineEdit_DataFolder.setReadOnly(True)
        self.lineEdit_DataFolder.setObjectName("lineEdit_DataFolder")
        self.gridLayout_6.addWidget(self.lineEdit_DataFolder, 1, 1, 1, 1)
        self.btn_Browse_DataFolder = QtWidgets.QPushButton(
            self.widget_top)
        self.btn_Browse_DataFolder.setObjectName(
            "btn_Browse_DataFolder")

        self.gridLayout_6.addWidget(
            self.btn_Browse_DataFolder, 1, 2, 1, 1)
        self.label_input_2 = QtWidgets.QLabel(self.widget_top)
        self.label_input_2.setObjectName("label_input_2")
        self.gridLayout_6.addWidget(self.label_input_2, 2, 0, 1, 3)
        self.label_Tonecpp = QtWidgets.QLabel(self.widget_top)
        self.label_Tonecpp.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_Tonecpp.setObjectName("label_Tonecpp")
        self.gridLayout_6.addWidget(self.label_Tonecpp, 3, 0, 1, 1)
        self.lineEdit_Tonecpp = QtWidgets.QLineEdit(self.widget_top)
        # self.lineEdit_Tonecpp.setReadOnly(True)
        self.lineEdit_Tonecpp.setObjectName("lineEdit_Tonecpp")
        self.gridLayout_6.addWidget(self.lineEdit_Tonecpp, 3, 1, 1, 1)
        self.btn_Browse_Tonecpp = QtWidgets.QPushButton(
            self.widget_top)
        self.btn_Browse_Tonecpp.setObjectName(
            "btn_Browse_Tonecpp")
        self.gridLayout_6.addWidget(self.btn_Browse_Tonecpp, 3, 2, 1, 1)
        self.label_Input = QtWidgets.QLabel(self.widget_top)
        self.label_Input.setObjectName("label_Input")
        self.gridLayout_6.addWidget(self.label_Input, 0, 0, 1, 3)
        
        self.btn_download_1 = QtWidgets.QToolButton(self.widget_top)
        self.btn_download_1.setGeometry(QtCore.QRect(419, 105, 30, 30))
        self.btn_download_1.setStyleSheet("")
        self.btn_download_1.setText("")
        self.btn_download_1.setAutoRaise(True)
        self.btn_download_1.setObjectName("btn_download_1")
        self.btn_download_1.setIcon(
            QIcon("./MTK/AE/Analysis/ToneCategorizer/icon_download.png"))
        self.btn_download_1.setStyleSheet("QToolButton{border:0px solid;}")
        self.btn_explain_1 = QtWidgets.QPushButton(self.widget_top)
        self.btn_explain_1.setGeometry(QtCore.QRect(457, 105, 30, 30))
        self.btn_explain_1.setObjectName("btn_explain_1")
        self.btn_explain_1.setIcon(
            QIcon("./MTK/AE/Analysis/ToneCategorizer/icon_explain.png"))
        self.btn_explain_1.setIconSize(QSize(25, 25))
        self.btn_explain_1.setStyleSheet("QToolButton{border:0px solid;}")
        
        
        
        self.widget_bot = QtWidgets.QWidget()
        # self.widget_bot.setGeometry(QtCore.QRect(20, 500, 450, 200))
        self.widget_bot.setObjectName("widget_bot")
        self.widget_bot.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        
        #############
        self.label_bot_description = QtWidgets.QLabel(self.widget_bot)
        self.label_bot_description.setObjectName("label_bot_description")
        # self.label_bot_description.setGeometry(0, 0, 0, 0)#####
        self.label_bot_description.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_bot_description.setStyleSheet(
            "border:1px solid white;border-style: dashed")
        self.label_bot_description.setWordWrap(True)
        
        self.botLayout = QtWidgets.QVBoxLayout(self.widget_bot)
        self.botLayout.setObjectName("botLayout")
        self.botLayout.addWidget(self.label_bot_description)

        self.btn_Update = QtWidgets.QPushButton(self.widget_bot)
        self.btn_Update.setObjectName("btn_Update")
        self.btn_Update.setGeometry(50, 145, 87, 32)
        
    
        self.btn_download_2 = QtWidgets.QToolButton(self.widget_bot)
        self.btn_download_2.setGeometry(QtCore.QRect(355, 70, 30, 30))
        self.btn_download_2.setStyleSheet("")
        self.btn_download_2.setText("")
        self.btn_download_2.setAutoRaise(True)
        self.btn_download_2.setObjectName("btn_download_2")
        self.btn_download_2.setIcon(
            QIcon("./MTK/AE/Analysis/ToneCategorizer/icon_download.png"))
        self.btn_download_2.setStyleSheet("QToolButton{border:0px solid;}")
        self.btn_explain_2 = QtWidgets.QPushButton(self.widget_bot)
        self.btn_explain_2.setGeometry(QtCore.QRect(235, 112, 30, 30))
        self.btn_explain_2.setObjectName("btn_explain_2")
        self.btn_explain_2.setIcon(
            QIcon("./MTK/AE/Analysis/ToneCategorizer/icon_explain.png"))
        self.btn_explain_2.setIconSize(QSize(25, 25))
        self.btn_explain_2.setStyleSheet("QToolButton{border:0px solid;}")
        
        ###############
        self.allLayout.addWidget(self.widget_top)
        self.allLayout.addWidget(self.widget_mid)
        self.allLayout.addWidget(self.widget_bot)
        self.scrollArea_all.setWidget(self.scrollAreaWidgetContents_all)
        self.showLayout.addWidget(self.scrollArea_all)
        #################

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form) 
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_Update.setText(_translate("Form", "Update"))
        self.label_bot_description.setText(_translate("Form", "Is data showing \"#NAME\"?\n"
                                         "Adjust Excel function name for different versions.\n"
                                         "Follow steps to solve:\n"
                                         "    1. Download XLOOKUPs to your computer.\n\n"
                                         "    2. Set XLOOKUPs to Excel.\n\n"))
        self.label_LR_max.setText(_translate("Form", "*Maximum 180"))
        self.label_RS_description.setText(_translate(
            "Form", "If unsure how to setting, test default fit."))
        self.label_17.setText(_translate("Form", "~"))
        self.label_20.setText(_translate("Form", "~"))
        self.label_14.setText(_translate("Form", "~"))
        self.label_16.setText(_translate("Form", "~"))
        self.label_DR8.setText(_translate("Form", "DR8:"))
        self.label_19.setText(_translate("Form", "~"))
        self.label_DR10.setText(_translate("Form", "DR10:"))
        self.label_DR2.setText(_translate("Form", "DR2:"))
        self.label_DR7.setText(_translate("Form", "DR7:"))
        self.label_18.setText(_translate("Form", "~"))
        self.label_15.setText(_translate("Form", "~"))
        self.label_DR9.setText(_translate("Form", "DR9:"))
        self.label_12.setText(_translate("Form", "~"))
        self.label_DR4.setText(_translate("Form", "DR4:"))
        self.lineEdit_DR3.setText(_translate("Form", "250"))
        self.label_13.setText(_translate("Form", "~"))
        self.label_DR1.setText(_translate("Form", "DR1:"))
        self.label_DR3.setText(_translate("Form", "DR3:"))
        self.lineEdit_DR5.setText(_translate("Form", "650"))
        self.lineEdit_DR1.setText(_translate("Form", "1"))
        self.lineEdit_DR4.setText(_translate("Form", "450"))
        self.lineEdit_DR2.setText(_translate("Form", "50"))
        self.label_11.setText(_translate("Form", "~"))
        self.label_DR5.setText(_translate("Form", "DR5:"))
        self.label_DR6.setText(_translate("Form", "DR6:"))
        self.label_DR_max.setText(_translate("Form", "*Maximum 1000"))
        self.label_LV1.setText(_translate("Form", "LV1:"))
        self.lineEdit_LV1.setText(_translate("Form", "1"))
        self.label.setText(_translate("Form", "~"))
        self.label_LV2.setText(_translate("Form", "LV2:"))
        self.lineEdit_LV2.setText(_translate("Form", "25"))
        self.label_2.setText(_translate("Form", "~"))
        self.label_LV3.setText(_translate("Form", "LV3:"))
        self.lineEdit_LV3.setText(_translate("Form", "55"))
        self.label_3.setText(_translate("Form", "~"))
        self.label_LV4.setText(_translate("Form", "LV4:"))
        self.lineEdit_LV4.setText(_translate("Form", "85"))
        self.label_4.setText(_translate("Form", "~"))
        self.label_LV5.setText(_translate("Form", "LV5:"))
        self.lineEdit_LV5.setText(_translate("Form", "115"))
        self.label_5.setText(_translate("Form", "~"))
        self.label_LV6.setText(_translate("Form", "LV6:"))
        self.lineEdit_LV6.setText(_translate("Form", "135"))
        self.label_6.setText(_translate("Form", "~"))
        self.label_LV7.setText(_translate("Form", "LV7:"))
        self.label_7.setText(_translate("Form", "~"))
        self.label_LV8.setText(_translate("Form", "LV8:"))
        self.label_8.setText(_translate("Form", "~"))
        self.label_LV9.setText(_translate("Form", "LV9:"))
        self.label_9.setText(_translate("Form", "~"))
        self.label_LV10.setText(_translate("Form", "LV10:"))
        self.label_10.setText(_translate("Form", "~"))
        self.btn_Reset.setText(_translate("Form", "Reset"))
        self.btn_OpenFolder.setText(_translate("Form", "Open Folder"))
        self.btn_Category.setText(_translate("Form", "Category"))
        self.label_RangeSettings.setText(
            _translate("Form", "------Range Settings------"))
        self.label_DataFolder.setText(_translate("Form", "Data folder:"))
        self.btn_Browse_DataFolder.setText(_translate("Form", "Browse"))
        self.label_input_2.setText(_translate("Form", "* Required data in the folder:\n"
                                              "  1. ref & tst pic must be encoded.\n"
                                              "  2. tst pic ISP module Exif.(Use MTK tool/ DebugParser      )         "))
        self.label_Tonecpp.setText(_translate("Form", "Tone.cpp:"))
        self.btn_Browse_Tonecpp.setText(_translate("Form", "Browse"))
        self.label_Input.setText(_translate("Form", "------Input------"))
        self.lineEdit_LV1_2.setText(_translate("Form", "25"))
        self.lineEdit_LV2_2.setText(_translate("Form", "55"))
        self.lineEdit_LV3_2.setText(_translate("Form", "85"))
        self.lineEdit_LV4_2.setText(_translate("Form", "115"))
        self.lineEdit_LV5_2.setText(_translate("Form", "135"))
        self.lineEdit_LV6_2.setText(_translate("Form", "180"))
        self.lineEdit_LV7_2.setText(_translate("Form", ""))
        self.lineEdit_LV8_2.setText(_translate("Form", ""))
        self.lineEdit_LV9_2.setText(_translate("Form", ""))
        self.lineEdit_LV10_2.setText(_translate("Form", ""))

        self.lineEdit_DR1_2.setText(_translate("Form", "50"))
        self.lineEdit_DR2_2.setText(_translate("Form", "250"))
        self.lineEdit_DR3_2.setText(_translate("Form", "450"))
        self.lineEdit_DR4_2.setText(_translate("Form", "650"))
        self.lineEdit_DR5_2.setText(_translate("Form", "1000"))
        self.lineEdit_DR6_2.setText(_translate("Form", ""))
        self.lineEdit_DR7_2.setText(_translate("Form", ""))
        self.lineEdit_DR8_2.setText(_translate("Form", ""))
        self.lineEdit_DR9_2.setText(_translate("Form", ""))
        self.lineEdit_DR10_2.setText(_translate("Form", ""))
        
        self.logic_handler = LogicHandler(self)
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    Form.setFixedSize(589, 739)
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
