# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(930, 638)
        font = QtGui.QFont()
        font.setPointSize(15)
        Form.setFont(font)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 906, 614))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.load_exif_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.load_exif_btn.setMinimumSize(QtCore.QSize(200, 60))
        self.load_exif_btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.load_exif_btn.setStyleSheet("text-align:center;\n"
"background:rgb(68, 114, 196); \n"
"color:rgb(255, 255, 255);")
        self.load_exif_btn.setObjectName("load_exif_btn")
        self.horizontalLayout_2.addWidget(self.load_exif_btn)
        self.open_dir_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.open_dir_btn.setMinimumSize(QtCore.QSize(200, 60))
        self.open_dir_btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.open_dir_btn.setStyleSheet("text-align:center;\n"
"background:rgb(68, 114, 196); \n"
"color:rgb(255, 255, 255);")
        self.open_dir_btn.setObjectName("open_dir_btn")
        self.horizontalLayout_2.addWidget(self.open_dir_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.THD_radio = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.THD_radio.setFont(font)
        self.THD_radio.setObjectName("THD_radio")
        self.button_group = QtWidgets.QButtonGroup(Form)
        self.button_group.setObjectName("button_group")
        self.button_group.addButton(self.THD_radio)
        self.horizontalLayout.addWidget(self.THD_radio)
        self.weighting_radio = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.weighting_radio.setFont(font)
        self.weighting_radio.setObjectName("weighting_radio")
        self.button_group.addButton(self.weighting_radio)
        self.horizontalLayout.addWidget(self.weighting_radio)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.BV_comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.BV_comboBox.setFont(font)
        self.BV_comboBox.setStyleSheet("font:18px ;\n"
"text-align:center;")
        self.BV_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.BV_comboBox.setObjectName("BV_comboBox")
        self.horizontalLayout_3.addWidget(self.BV_comboBox)
        self.B2D_EVD_comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.B2D_EVD_comboBox.setFont(font)
        self.B2D_EVD_comboBox.setStyleSheet("font:18px ;\n"
"text-align:center;")
        self.B2D_EVD_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.B2D_EVD_comboBox.setObjectName("B2D_EVD_comboBox")
        self.horizontalLayout_3.addWidget(self.B2D_EVD_comboBox)
        self.Mid_B2M_comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Mid_B2M_comboBox.setFont(font)
        self.Mid_B2M_comboBox.setStyleSheet("font:18px ;\n"
"text-align:center;")
        self.Mid_B2M_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.Mid_B2M_comboBox.setObjectName("Mid_B2M_comboBox")
        self.horizontalLayout_3.addWidget(self.Mid_B2M_comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 880, 484))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.photo_grid = QtWidgets.QGridLayout()
        self.photo_grid.setObjectName("photo_grid")
        self.verticalLayout_2.addLayout(self.photo_grid)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_4.addWidget(self.scrollArea_2)
        self.horizontalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.load_exif_btn.setText(_translate("Form", "選擇照片、exif 資料夾\n"
"並執行分類"))
        self.open_dir_btn.setText(_translate("Form", "開啟對應\n"
" region資料夾"))
        self.THD_radio.setText(_translate("Form", "THD"))
        self.weighting_radio.setText(_translate("Form", "Weighting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
