# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1260, 841)
        font = QtGui.QFont()
        font.setPointSize(15)
        Form.setFont(font)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.weighting_radio = QtWidgets.QRadioButton(Form)
        self.weighting_radio.setGeometry(QtCore.QRect(100, 70, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.weighting_radio.setFont(font)
        self.weighting_radio.setObjectName("weighting_radio")
        self.open_dir_btn = QtWidgets.QPushButton(Form)
        self.open_dir_btn.setGeometry(QtCore.QRect(240, 10, 251, 51))
        self.open_dir_btn.setStyleSheet("font:20px ;\n"
"text-align:center;\n"
"background:rgb(68, 114, 196); \n"
"color:rgb(255, 255, 255);")
        self.open_dir_btn.setObjectName("open_dir_btn")
        self.load_exif_btn = QtWidgets.QPushButton(Form)
        self.load_exif_btn.setGeometry(QtCore.QRect(10, 10, 221, 51))
        self.load_exif_btn.setStyleSheet("font:20px ;\n"
"text-align:center;\n"
"background:rgb(68, 114, 196); \n"
"color:rgb(255, 255, 255);")
        self.load_exif_btn.setObjectName("load_exif_btn")
        self.THD_radio = QtWidgets.QRadioButton(Form)
        self.THD_radio.setGeometry(QtCore.QRect(10, 70, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.THD_radio.setFont(font)
        self.THD_radio.setObjectName("THD_radio")
        self.BV_comboBox = QtWidgets.QComboBox(Form)
        self.BV_comboBox.setGeometry(QtCore.QRect(240, 80, 89, 24))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.BV_comboBox.setFont(font)
        self.BV_comboBox.setStyleSheet("font:18px ;\n"
"text-align:center;")
        self.BV_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.BV_comboBox.setObjectName("BV_comboBox")
        self.BV_comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(440, 80, 87, 24))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("font:18px ;\n"
"text-align:center;")
        self.comboBox_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(640, 80, 87, 24))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("font:18px ;\n"
"text-align:center;")
        self.comboBox_3.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalScrollBar = QtWidgets.QScrollBar(Form)
        self.verticalScrollBar.setGeometry(QtCore.QRect(640, 160, 16, 561))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.weighting_radio.setText(_translate("Form", "Weighting"))
        self.open_dir_btn.setText(_translate("Form", "開啟對應\n"
" region資料夾"))
        self.load_exif_btn.setText(_translate("Form", "選擇照片、exif 資料夾\n"
"並執行分類"))
        self.THD_radio.setText(_translate("Form", "THD"))
        self.BV_comboBox.setItemText(0, _translate("Form", "BV區間"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
