# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(668, 310)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(100, 40, 496, 201))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_photoFolder = QtWidgets.QLabel(self.widget)
        self.label_photoFolder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_photoFolder.setObjectName("label_photoFolder")
        self.gridLayout.addWidget(self.label_photoFolder, 0, 0, 1, 1)
        self.lineEdit_photoFolderPath = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_photoFolderPath.setObjectName("lineEdit_photoFolderPath")
        self.gridLayout.addWidget(self.lineEdit_photoFolderPath, 0, 1, 1, 1)
        self.btn_browse = QtWidgets.QPushButton(self.widget)
        self.btn_browse.setStyleSheet("background: rgb(48, 87, 164);\n"
"color: white")
        self.btn_browse.setObjectName("btn_browse")
        self.gridLayout.addWidget(self.btn_browse, 0, 2, 1, 1)
        self.label_photoFolderHint = QtWidgets.QLabel(self.widget)
        self.label_photoFolderHint.setObjectName("label_photoFolderHint")
        self.gridLayout.addWidget(self.label_photoFolderHint, 1, 1, 1, 1)
        self.label_keyword = QtWidgets.QLabel(self.widget)
        self.label_keyword.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_keyword.setObjectName("label_keyword")
        self.gridLayout.addWidget(self.label_keyword, 2, 0, 1, 1)
        self.lineEdit_keyword = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_keyword.setObjectName("lineEdit_keyword")
        self.gridLayout.addWidget(self.lineEdit_keyword, 2, 1, 1, 1)
        self.label_keywordHint = QtWidgets.QLabel(self.widget)
        self.label_keywordHint.setObjectName("label_keywordHint")
        self.gridLayout.addWidget(self.label_keywordHint, 3, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_implement = QtWidgets.QPushButton(self.widget)
        self.btn_implement.setObjectName("btn_implement")
        self.horizontalLayout.addWidget(self.btn_implement)
        self.btn_openFolder = QtWidgets.QPushButton(self.widget)
        self.btn_openFolder.setObjectName("btn_openFolder")
        self.horizontalLayout.addWidget(self.btn_openFolder)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_photoFolder.setText(_translate("Form", "Photo folder:"))
        self.btn_browse.setText(_translate("Form", "Browse"))
        self.label_photoFolderHint.setText(_translate("Form", "<html><head/><body><p>* Photos must be encoded.<br/>&nbsp;&nbsp;&nbsp;Ex: 1_E7.jpg, 1_SX3.jpg, 1_DG1.jpg...</p></body></html>"))
        self.label_keyword.setText(_translate("Form", "Keyword:"))
        self.label_keywordHint.setText(_translate("Form", "<html><head/><body><p>* Fill in the desired ISO file name keyword to apply.<br/>&nbsp;&nbsp;&nbsp;Ex: SX3 or V1.23.</p></body></html>"))
        self.btn_implement.setText(_translate("Form", "Implement"))
        self.btn_openFolder.setText(_translate("Form", "Open folder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
