# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(601, 192)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 30, 461, 98))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_Browse = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_Browse.setStyleSheet("background: rgb(48, 87, 164);\n"
"color: white")
        self.btn_Browse.setObjectName("btn_Browse")
        self.gridLayout_2.addWidget(self.btn_Browse, 0, 2, 1, 1)
        self.label_Hint = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Hint.setObjectName("label_Hint")
        self.gridLayout_2.addWidget(self.label_Hint, 1, 1, 1, 1)
        self.label_PhotoFolder = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_PhotoFolder.setObjectName("label_PhotoFolder")
        self.gridLayout_2.addWidget(self.label_PhotoFolder, 0, 0, 1, 1)
        self.lineEdit_FolderPath = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_FolderPath.setObjectName("lineEdit_FolderPath")
        self.gridLayout_2.addWidget(self.lineEdit_FolderPath, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_Compute = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_Compute.setObjectName("btn_Compute")
        self.horizontalLayout_2.addWidget(self.btn_Compute)
        self.btn_OpenFolder = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_OpenFolder.setObjectName("btn_OpenFolder")
        self.horizontalLayout_2.addWidget(self.btn_OpenFolder)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_Browse.setText(_translate("Form", "Browse"))
        self.label_Hint.setText(_translate("Form", "* Recommend at least 10 photos."))
        self.label_PhotoFolder.setText(_translate("Form", "Photo Folder :"))
        self.btn_Compute.setText(_translate("Form", "Compute"))
        self.btn_OpenFolder.setText(_translate("Form", "Open folder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
