# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(534, 257)
        Form.setStyleSheet("")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 34, 359, 172))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_photo_folder = QtWidgets.QLabel(self.layoutWidget)
        self.label_photo_folder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_photo_folder.setObjectName("label_photo_folder")
        self.gridLayout.addWidget(self.label_photo_folder, 0, 0, 1, 1)
        self.lineEdit_photo_folder = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_photo_folder.setEnabled(False)
        self.lineEdit_photo_folder.setObjectName("lineEdit_photo_folder")
        self.gridLayout.addWidget(self.lineEdit_photo_folder, 0, 1, 1, 1)
        self.pushButton_photo_folder = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_photo_folder.setStyleSheet("background-color: #3b5998; /* Facebook Blue */\n"
"    border: 1px solid #2d4373; /* Darker Blue Border */\n"
"\n"
"    color: white;\n"
"    text-align: center;\n"
"\n"
"")
        self.pushButton_photo_folder.setObjectName("pushButton_photo_folder")
        self.gridLayout.addWidget(self.pushButton_photo_folder, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.label_photo_folder_explain = QtWidgets.QLabel(self.layoutWidget)
        self.label_photo_folder_explain.setStyleSheet("")
        self.label_photo_folder_explain.setObjectName("label_photo_folder_explain")
        self.gridLayout.addWidget(self.label_photo_folder_explain, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.comboBox_ours = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_ours.setObjectName("comboBox_ours")
        self.gridLayout.addWidget(self.comboBox_ours, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        self.label_EV_ratio = QtWidgets.QLabel(self.layoutWidget)
        self.label_EV_ratio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_EV_ratio.setObjectName("label_EV_ratio")
        self.gridLayout.addWidget(self.label_EV_ratio, 3, 0, 1, 1)
        self.lineEdit_EV_ratio = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_EV_ratio.setObjectName("lineEdit_EV_ratio")
        self.gridLayout.addWidget(self.lineEdit_EV_ratio, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 0, 1, 1)
        self.pushButton_run = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_run.setObjectName("pushButton_run")
        self.gridLayout.addWidget(self.pushButton_run, 4, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 4, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_photo_folder.setText(_translate("Form", "Photo folder:"))
        self.pushButton_photo_folder.setText(_translate("Form", "Browse"))
        self.label_photo_folder_explain.setText(_translate("Form", "* Photo must be encoded.\n"
"   Ex: 1_E7.jpg, 1_SX3.jpg"))
        self.label.setText(_translate("Form", "Ours:"))
        self.label_EV_ratio.setText(_translate("Form", "EV Ratio:"))
        self.lineEdit_EV_ratio.setText(_translate("Form", "6"))
        self.pushButton_run.setText(_translate("Form", "Run"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
