# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from myPackage.ImageViewer import ImageViewer
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QWidget, QHBoxLayout, QVBoxLayout
from PyQt5.QtCore import  Qt

import sys
sys.path.append("..")

class FFT_Block(QWidget):
    def __init__(self):
        super().__init__()
        HLayout = QHBoxLayout(self)
        HLayout.setContentsMargins(2, 2, 2, 2)
        HLayout.setSpacing(0)

        # ImageViewer
        self.img_viewer = ImageViewer()
        self.img_viewer.setStyleSheet("border: 2px solid white;")
        self.img_viewer.setAlignment(QtCore.Qt.AlignCenter)
        HLayout.addWidget(self.img_viewer, stretch=2)

        # fft viewer
        self.fft_viewer = ImageViewer()
        self.fft_viewer.setStyleSheet("border: 2px solid white;")
        self.fft_viewer.setAlignment(QtCore.Qt.AlignCenter)
        HLayout.addWidget(self.fft_viewer, stretch=2)

        self.fft_his = ImageViewer()
        self.fft_his.setAlignment(QtCore.Qt.AlignCenter)
        HLayout.addWidget(self.fft_his, stretch=3)

class Ui_MainWindow(object):
    def __init__(self) -> None:
        self.open_img_btn = []
        self.fft_block = []

    def setupUi(self, MainWindow):
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.VLayout_parent = QVBoxLayout(self.centralwidget)
        self.VLayout_parent.setContentsMargins(0, -10, 0, -10)
        self.VLayout_parent.setSpacing(0)

        # btn
        self.HLayout_btn = QHBoxLayout()
        self.HLayout_btn.setAlignment(Qt.AlignCenter)
        self.HLayout_btn.setContentsMargins(5, 5, 5, 5)
        self.HLayout_btn.setSpacing(15)
        for i in range(4):
            btn = QtWidgets.QPushButton("load PIC"+str(i+1))
            self.HLayout_btn.addWidget(btn)
            self.open_img_btn.append(btn)

        self.VLayout_parent.addLayout(self.HLayout_btn)


        # fft block
        for i in range(4):
            fft_block = FFT_Block()
            fft_block.hide()
            self.VLayout_parent.addWidget(fft_block)
            self.fft_block.append(fft_block)
       
        MainWindow.setCentralWidget(self.centralwidget)

        MainWindow.setStyleSheet("QMainWindow {background-color: rgb(66, 66, 66);}"
                                 """
                                QLabel {
                                    font-size:14pt; font-family:微軟正黑體; font-weight: bold;
                                    background-color: rgb(255, 255, 255);
                                    border-color: rgb(0, 0, 0);
                                    border-width : 1.2px;
                                    border-style:inset;
                                    }
                                """
                                 "QPushButton {font-size:14pt; font-family:微軟正黑體; font-weight: bold; background-color:rgb(255, 170, 0);}")


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FFT Analysis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
