# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(832, 469)
        Form.setStyleSheet("font-family:微軟正黑體;\n"
"font-weight: bold;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 808, 445))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.setting_layout = QtWidgets.QVBoxLayout()
        self.setting_layout.setObjectName("setting_layout")
        self.project_layout = QtWidgets.QGridLayout()
        self.project_layout.setObjectName("project_layout")
        self.load_project_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_project_btn.sizePolicy().hasHeightForWidth())
        self.load_project_btn.setSizePolicy(sizePolicy)
        self.load_project_btn.setObjectName("load_project_btn")
        self.project_layout.addWidget(self.load_project_btn, 0, 0, 1, 1)
        self.project_path = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.project_path.setObjectName("project_path")
        self.project_layout.addWidget(self.project_path, 0, 1, 1, 1)
        self.project_layout.setColumnStretch(0, 2)
        self.project_layout.setColumnStretch(1, 5)
        self.setting_layout.addLayout(self.project_layout)
        self.trigger_grid = QtWidgets.QGridLayout()
        self.trigger_grid.setObjectName("trigger_grid")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.trigger_grid.addWidget(self.label_5, 2, 0, 1, 1)
        self.saved_dir = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.saved_dir.setObjectName("saved_dir")
        self.trigger_grid.addWidget(self.saved_dir, 0, 1, 1, 1)
        self.set_saved_dir_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.set_saved_dir_btn.setObjectName("set_saved_dir_btn")
        self.trigger_grid.addWidget(self.set_saved_dir_btn, 0, 0, 1, 1)
        self.load_txt_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.load_txt_btn.setObjectName("load_txt_btn")
        self.trigger_grid.addWidget(self.load_txt_btn, 1, 0, 1, 1)
        self.param_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.param_label.setText("")
        self.param_label.setObjectName("param_label")
        self.trigger_grid.addWidget(self.param_label, 2, 1, 1, 1)
        self.txt_path_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.txt_path_label.setText("")
        self.txt_path_label.setObjectName("txt_path_label")
        self.trigger_grid.addWidget(self.txt_path_label, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.trigger_grid.addWidget(self.label_8, 3, 0, 1, 1)
        self.img_path_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img_path_label.setText("")
        self.img_path_label.setObjectName("img_path_label")
        self.trigger_grid.addWidget(self.img_path_label, 3, 1, 1, 1)
        self.trigger_grid.setColumnStretch(0, 2)
        self.trigger_grid.setColumnStretch(1, 5)
        self.setting_layout.addLayout(self.trigger_grid)
        self.verticalLayout.addLayout(self.setting_layout)
        self.capture_layout = QtWidgets.QVBoxLayout()
        self.capture_layout.setObjectName("capture_layout")
        self.start_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.start_btn.setObjectName("start_btn")
        self.capture_layout.addWidget(self.start_btn)
        self.verticalLayout.addLayout(self.capture_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.load_project_btn.setText(_translate("Form", "Load Project"))
        self.project_path.setText(_translate("Form", "#"))
        self.label_5.setText(_translate("Form", "param"))
        self.saved_dir.setText(_translate("Form", "儲存照片的資料夾"))
        self.set_saved_dir_btn.setText(_translate("Form", "Set Photo Dir"))
        self.load_txt_btn.setText(_translate("Form", "Load param.txt"))
        self.label_8.setText(_translate("Form", "img name"))
        self.start_btn.setText(_translate("Form", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
