# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(976, 537)
        Form.setStyleSheet("font-family:微軟正黑體;\n"
"font-weight: bold;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 952, 513))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.setting_layout = QtWidgets.QVBoxLayout()
        self.setting_layout.setObjectName("setting_layout")
        self.project_grid = QtWidgets.QGridLayout()
        self.project_grid.setObjectName("project_grid")
        self.load_project_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_project_btn.sizePolicy().hasHeightForWidth())
        self.load_project_btn.setSizePolicy(sizePolicy)
        self.load_project_btn.setObjectName("load_project_btn")
        self.project_grid.addWidget(self.load_project_btn, 0, 0, 1, 1)
        self.project_path = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.project_path.setObjectName("project_path")
        self.project_grid.addWidget(self.project_path, 0, 1, 1, 1)
        self.project_grid.setColumnStretch(0, 2)
        self.project_grid.setColumnStretch(1, 5)
        self.setting_layout.addLayout(self.project_grid)
        self.save_grid = QtWidgets.QGridLayout()
        self.save_grid.setObjectName("save_grid")
        self.set_saved_dir_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.set_saved_dir_btn.setObjectName("set_saved_dir_btn")
        self.save_grid.addWidget(self.set_saved_dir_btn, 0, 0, 1, 1)
        self.saved_dir = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.saved_dir.setObjectName("saved_dir")
        self.save_grid.addWidget(self.saved_dir, 0, 1, 1, 1)
        self.save_grid.setColumnStretch(0, 2)
        self.save_grid.setColumnStretch(1, 5)
        self.setting_layout.addLayout(self.save_grid)
        self.verticalLayout.addLayout(self.setting_layout)
        self.capture_layout = QtWidgets.QVBoxLayout()
        self.capture_layout.setObjectName("capture_layout")
        self.start_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_btn.sizePolicy().hasHeightForWidth())
        self.start_btn.setSizePolicy(sizePolicy)
        self.start_btn.setObjectName("start_btn")
        self.capture_layout.addWidget(self.start_btn)
        self.progressBar = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.capture_layout.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.capture_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.load_project_btn.setText(_translate("Form", "Load Project"))
        self.project_path.setText(_translate("Form", "#"))
        self.set_saved_dir_btn.setText(_translate("Form", "Set Dataset Dir"))
        self.saved_dir.setText(_translate("Form", "儲存資料集的位置"))
        self.start_btn.setText(_translate("Form", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
