# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(832, 353)
        Form.setStyleSheet("font-family:微軟正黑體;\n"
"font-weight: bold;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.setting_layout = QtWidgets.QVBoxLayout()
        self.setting_layout.setObjectName("setting_layout")
        self.label_7 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;\n"
"padding: 5px;\n"
"border-bottom: 10px solid black;")
        self.label_7.setObjectName("label_7")
        self.setting_layout.addWidget(self.label_7)
        self.platform_grid = QtWidgets.QGridLayout()
        self.platform_grid.setObjectName("platform_grid")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.platform_grid.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.platform_grid.addWidget(self.label, 0, 0, 1, 1)
        self.platform_grid.setColumnStretch(0, 2)
        self.platform_grid.setColumnStretch(1, 5)
        self.setting_layout.addLayout(self.platform_grid)
        self.project_layout = QtWidgets.QGridLayout()
        self.project_layout.setObjectName("project_layout")
        self.load_project_btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_project_btn.sizePolicy().hasHeightForWidth())
        self.load_project_btn.setSizePolicy(sizePolicy)
        self.load_project_btn.setObjectName("load_project_btn")
        self.project_layout.addWidget(self.load_project_btn, 0, 0, 1, 1)
        self.project_path = QtWidgets.QLabel(Form)
        self.project_path.setObjectName("project_path")
        self.project_layout.addWidget(self.project_path, 0, 1, 1, 1)
        self.project_layout.setColumnStretch(0, 2)
        self.project_layout.setColumnStretch(1, 5)
        self.setting_layout.addLayout(self.project_layout)
        self.trigger_grid = QtWidgets.QGridLayout()
        self.trigger_grid.setObjectName("trigger_grid")
        self.set_saved_dir_btn = QtWidgets.QPushButton(Form)
        self.set_saved_dir_btn.setObjectName("set_saved_dir_btn")
        self.trigger_grid.addWidget(self.set_saved_dir_btn, 3, 0, 1, 1)
        self.trigger_comboBox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trigger_comboBox.sizePolicy().hasHeightForWidth())
        self.trigger_comboBox.setSizePolicy(sizePolicy)
        self.trigger_comboBox.setObjectName("trigger_comboBox")
        self.trigger_grid.addWidget(self.trigger_comboBox, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.trigger_grid.addWidget(self.label_3, 2, 0, 1, 1)
        self.saved_dir = QtWidgets.QLabel(Form)
        self.saved_dir.setObjectName("saved_dir")
        self.trigger_grid.addWidget(self.saved_dir, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.trigger_grid.addWidget(self.label_4, 1, 0, 1, 1)
        self.bin_name_edit = QtWidgets.QLineEdit(Form)
        self.bin_name_edit.setObjectName("bin_name_edit")
        self.trigger_grid.addWidget(self.bin_name_edit, 1, 1, 1, 1)
        self.load_exe_btn = QtWidgets.QPushButton(Form)
        self.load_exe_btn.setObjectName("load_exe_btn")
        self.trigger_grid.addWidget(self.load_exe_btn, 0, 0, 1, 1)
        self.exe_path = QtWidgets.QLabel(Form)
        self.exe_path.setObjectName("exe_path")
        self.trigger_grid.addWidget(self.exe_path, 0, 1, 1, 1)
        self.trigger_grid.setColumnStretch(0, 2)
        self.trigger_grid.setColumnStretch(1, 5)
        self.setting_layout.addLayout(self.trigger_grid)
        self.verticalLayout_2.addLayout(self.setting_layout)
        self.capture_layout = QtWidgets.QVBoxLayout()
        self.capture_layout.setObjectName("capture_layout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;\n"
"padding: 5px;\n"
"border-bottom: 10px solid black;")
        self.label_2.setObjectName("label_2")
        self.capture_layout.addWidget(self.label_2)
        self.start_capture_btn = QtWidgets.QPushButton(Form)
        self.start_capture_btn.setObjectName("start_capture_btn")
        self.capture_layout.addWidget(self.start_capture_btn)
        self.verticalLayout_2.addLayout(self.capture_layout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "Setting"))
        self.radioButton_2.setText(_translate("Form", "c6project"))
        self.radioButton.setText(_translate("Form", "c7project"))
        self.label.setText(_translate("Form", "platform"))
        self.load_project_btn.setText(_translate("Form", "Load Project"))
        self.project_path.setText(_translate("Form", "#"))
        self.set_saved_dir_btn.setText(_translate("Form", "Set Dataset Dir"))
        self.label_3.setText(_translate("Form", "trigger_idx(region)"))
        self.saved_dir.setText(_translate("Form", "儲存資料集的位置"))
        self.label_4.setText(_translate("Form", "bin name"))
        self.bin_name_edit.setText(_translate("Form", "com.qti.tuned.shinetech_s5k3l6.bin"))
        self.load_exe_btn.setText(_translate("Form", "Load ParameterParser.exe"))
        self.exe_path.setText(_translate("Form", "#"))
        self.label_2.setText(_translate("Form", "開始拍攝"))
        self.start_capture_btn.setText(_translate("Form", "開始拍攝"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
